version: '3.3'

services:
  historias_c:
    image: soyachin/api-historia-clinica
    ports: 8081:8000
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
  doctores_c:
    image: soyachin/api-doctores
    ports: 8082:3000
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
  pacientes_c:
    image: soyachin/api-pacientes
    ports: 8083:8000
    environment:
      - MONGO_URI=${MONGO_URI}    
      
